#!/bin/sh

rm -f quux inode_pre inode_post baz
set -x
cat safewrite safewrite safewrite safewrite safewrite > quux || exit 1
cp quux baz || exit 1
ls -i quux > inode_pre
./safewrite -s quux cat baz || exit 1
ls -i quux > inode_post
if cmp -s inode_pre inode_post
then
	: File was not replaced
else
	: File was replaced
	exit 1
fi
exec cmp quux baz
